### ISSUE TITLE
Request for Help for Newb

### ISSUE THREAD

**Issue by finkelsteinberg** [Pakuna/foescripts#1]
Can you provide a bit more detail on how to get this script to run? It looks like I need the FoE Helper extension which I have. I am using Google Chrome. I've tried running it by injecting the javascript in to the browser but that doesn't seem to work. Any help would be greatly appreciated.

**Comment by Pakuna** [comment]
😲 First comment ever on GitHub! Thank you for your interest!

Just updated the README.md with a little bit of documentation. Happy to answer further questions 🙃 But I guess at this stage it needs quite a bit of JavaScript knowledge to read the code yourself to really understand whats going on..
